###

# curl -X POST -H 'Content-Type: application/json' -d '{"scheduler_time" :
#"2021-11-12T17:00:00", "lines":"victoria"}' http://localhost:5555/tasks
POST http://localhost:5555/tasks
Content-Type: application/json

{
  "scheduler_time": "2021-11-12T17:00:00",
  "lines": "victoria"
}

###

# curl -X POST -H 'Content-Type: application/json' -d '{"scheduler_time" :
#"2021-11-12T17:00:00", "lines":"victoria,central"}'
#http://localhost:5555/tasks
POST http://localhost:5555/tasks
Content-Type: application/json

{
  "scheduler_time": "2021-11-12T17:00:00",
  "lines": "victoria,central"
}

###

